version: '3.8'

services:
  # This is the service for your Node.js MineControl app
  controller-app:
    build: .
    container_name: minecontrol_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      # Mount the host's Docker socket into the container to run 'docker' commands on the host
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - minecraft-server

  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    restart: on-failure
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.8"
      MEMORY: "5G"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ${MINECRAFT_DATA_PATH}:/data